spring:
  data:
    mongodb:
      uri: mongodb://mongodb.test.svc.cluster.local:27019/ail-location
  datasource:
    url: jdbc:mysql://mysql-svc.dev.svc.cluster.local:3306/xsun_gps?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: mysql_password
  redis:
    database: 0
    host: redis-svc.dev.svc.cluster.local
    port: 6379
  rabbitmq:
    addresses: rabbitmq-svc.dev.svc.cluster.local
    port: 61613
    username: user
    password: password
swagger:
  enable: true
abs:
  queue:
    default: abs.default.dev
jimi:
  expires_in: 100
  mapType_google: GOOGLE
xinya:
  xsungroupurl: http://xinya-svc.dev.svc.cluster.local:8080
scheduler:
  close: true
xinya-external: http://dev-external.xsungroup.cn
xinya-message: http://dev-stomp.xsungroup.cn
